### ISSUE TITLE
Community Application

### ISSUE THREAD

**Issue by geektutor** [30DaysOfCode/node-be#8]
External 30DoC - a community lead will apply to us. When application is approved, they will generate a 5-10 code for the 30DoC that they want to do. 

Community Application Form and tier level.

We need to talk about the flow.

**Comment by bolubee101** [comment]
I have a question about external 30 days of code. So is it an individual that would apply, or an organization? 

Moving on, if say DSC unilag wanted to organize a 30days of code, how would the application be? Should DSC unilag apply with it's own account to host a 30 DoC? or is it the lead at the point in time with their own account that would apply?

I propose we have a register as an organization option in case of reoccurring applications from a single organization that might have different management at any point in time.

As for the 5-10 character ID, I think all 30DOC should have it, that way it's a single logic system that handles any 30DoC created.

Also, I need a bit of clarification with regards to tiers concerning external 30DoC applications and their functionality. Would it be the equivalent of the individual participation tier class like thus:  free tier has access to only uploading questions. Tier 1 - add mentor who would give review. Tier 2 - Issue out certificates.

**Comment by geektutor** [comment]
> I have a question about external 30 days of code. So is it an individual that would apply, or an organization?

An individual will apply and fill a form to open a 30DoC for their organization/group. What are the form fields? @Ifihan @Emmanuerl 
> Moving on, if say DSC unilag wanted to organize a 30days of code, how would the application be? Should DSC unilag apply with it's own account to host a 30 DoC? or is it the lead at the point in time with their own account that would apply?

This is also something to consider. Whether the lead can add new admins/managers to that organization or whether we(super admins) can add a new admin for them. Thoughts? 

I think we can have community opened but it is tied to a manager account.
> I propose we have a register as an organization option in case of reoccurring applications from a single organization that might have different management at any point in time.
 
I agree but a manager is applying for an organization but an organization can have multiple managers (say 2/3 max?) and if the lead is incapacitated, we can have them shoot an email to us and we add them as a manager.
> As for the 5-10 character ID, I think all 30DOC should have it, that way it's a single logic system that handles any 30DoC created.

How will this come in place for the normal 30DoC?
> Also, I need a bit of clarification with regards to tiers concerning external 30DoC applications and their functionality. Would it be the equivalent of the individual participation tier class like thus: free tier has access to only uploading questions. Tier 1 - add mentor who would give review. Tier 2 - Issue out certificates.

Tiers dont apply to external 30DoC. Since, we agreed that community organizers when applying will pay. So when they pay, they will have to add their own mentors (to review) and their own leaderboard. We haven't discussed certification and how it comes into play for them. I think they should get it. If we can make the process easy for them to generate cert for everyone, that would be great.

**Comment by Ifihan** [comment]
I think it should be the community's mail and we can have the external participation button/sign on the landing page. 

The fields of the forms would be: 
Community name 
Community mail 
Brief description of the community
Why they want to use the platform (poor wording)
Social media links 
Any other thing they want us to know

**Comment by geektutor** [comment]
> I think it should be the community's mail and we can have the external participation button/sign on the landing page.

So a normal user account will have to open a community email account? We can figure it on stand-up tonight

> The fields of the forms would be:
> Community name
> Community mail
> Brief description of the community
> Why they want to use the platform (poor wording)
> Social media links
> Any other thing they want us to know

I think this works. Then when they are approved, they pay?
